#!/bin/bash
echo "Content-type: text/plain; charset=iso-8859-1"
echo
mysql -u root -ppassword <<MY_QUERY
	CREATE DATABASE Escape;
	USE Escape;

	CREATE TABLE PRESENTER (PRESENTERID int(11) NOT NULL AUTO_INCREMENT, HANDLE varchar(100) NOT NULL, NAME VARCHAR(255), TOPIC VARCHAR(255), START TIMESTAMP DEFAULT '2017-06-30 00:00:00', END TIMESTAMP DEFAULT '2017-06-30 00:00:00', PRIMARY KEY(PRESENTERID));

	CREATE TABLE VOTES (VOTEID int(11) NOT NULL AUTO_INCREMENT, RATING int(11) DEFAULT 0, TIMESLOT int(11), PRIMARY KEY(VOTEID), FOREIGN KEY(TIMESLOT) REFERENCES PRESENTER(PRESENTERID));

	CREATE TABLE COMMENTS(COMMENTID INT AUTO_INCREMENT, COMMENT TEXT, PRESENTER INT, TWEETED BIT DEFAULT 0, TIME TIMESTAMP DEFAULT '2017-06-30 00:00:00', PRIMARY KEY(COMMENTID), FOREIGN KEY(PRESENTER) REFERENCES PRESENTER(PRESENTERID));

	CREATE USER 'bbd'@'localhost' IDENTIFIED BY 'password';
	GRANT ALL PRIVILEGES ON *.* TO 'bbd'@'localhost';
	FLUSH PRIVILEGES;
MY_QUERY
echo "Database created"
