<?php
	$conn = new mysqli("127.0.0.1", "bbd", "password","Escape", 3306);

	$sql = "SELECT MAX(AVERAGE) AS RATING, TIMESLOT,HANDLE, NAME, TOPIC FROM
		(SELECT AVG(RATING) AS AVERAGE,  TIMESLOT, HANDLE, NAME, TOPIC FROM VOTES LEFT JOIN PRESENTER ON PRESENTERID = TIMESLOT GROUP BY TIMESLOT) 
		AS MAXAVG";
	/*"SELECT SECTION, MAX(AVERAGE) AS RATING, HANDLE FROM 
		(SELECT AVERAGE, SECTION, TIMESLOT, HANDLE FROM (SELECT AVG(RATING) AS AVERAGE,  TIMESLOT FROM VOTES GROUP BY TIMESLOT) AS AVGSLOTS 
		LEFT JOIN PRESENTER ON PRESENTER.ID = AVGSLOTS.TIMESLOT) AS MAXSECTION GROUP BY SECTION";*/

	$result = $conn->query($sql);
	$output = array();
	while($row = $result->fetch_assoc()){
	   	$output[]=$row;
	}

	echo json_encode($output);
?>
